# Generated by Django 5.2.8 on 2026-02-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FinanceApp", "0002_transaction_status_userloanlimit"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="transaction",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending payment"), ("COMPLETED", "Completed")],
                default="COMPLETED",
                max_length=10,
            ),
        ),
    ]
